name: Build Mobile APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Nativefier
      run: npm install -g nativefier

    - name: Build APK/App
      run: |
        nativefier "https://kalyugkaravan9890-alt.github.io/Paradise-English-boarding-school-/" --name "Paradise School" --platform android --arch x64 --out output-app --ignore-certificate-errors

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Paradise-School-APK
        path: output-app/**/*.apk
